
Tensor Rank | Prog/Math | Python
--- | --- | ----
0 | scalar | int, float, string, bool
1 | vector | list, tuple, set, dict, string, array, series
2 | matrix | nested list, matrix, data frame, list of lists, array of arrays
3 |   | list of data frames, list of lists of lists, array of arrays of arrays

In [ ]:
import numpy as np

In [ ]:
foo = np.arange(2**6)
foo

In [4]:
foo.shape

(64,)

In [5]:
foo.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]])

In [6]:
foo.reshape(1,-1).shape

(1, 64)

In [7]:
foo.reshape(1, 2,-1)


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
         48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]]])

In [8]:
foo.reshape(1, 2,-1).shape

(1, 2, 32)

In [9]:
foo.reshape(2, 2,-1)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]]])

In [10]:
foo.reshape(2, 2, -1).shape

(2, 2, 16)

In [11]:
foo.reshape(2, 2, 2, -1)

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14, 15]],

        [[16, 17, 18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29, 30, 31]]],


       [[[32, 33, 34, 35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44, 45, 46, 47]],

        [[48, 49, 50, 51, 52, 53, 54, 55],
         [56, 57, 58, 59, 60, 61, 62, 63]]]])

In [12]:
foo.reshape(2, 2, 2, -1).shape

(2, 2, 2, 8)

In [13]:
foo.reshape(2, 2, 2, 2, -1).shape

(2, 2, 2, 2, 4)

In [14]:
foo.reshape(2, 2, 2, 2, 2, -1).shape

(2, 2, 2, 2, 2, 2)

In [15]:
foo.reshape(2, 2, 2, 2, 2, 2, -1).shape

(2, 2, 2, 2, 2, 2, 1)

In [16]:
foo.reshape(1, 2, 2, 2, 2, 2, 2, -1).shape

(1, 2, 2, 2, 2, 2, 2, 1)

In [23]:
len(foo.reshape(1, 1, 2, 2, 2, 2, 2, 2, -1).shape)

9

In [18]:
foo.reshape(1, 64).shape

(1, 64)

In [19]:
foo.reshape(1, 1, 64).shape

(1, 1, 64)

In [22]:
foo.reshape(1, -1, 2).flatten().shape


(64,)